import type { IdeaNode } from "./types";

/* The 9 project ideas that float in the cosmos. Detail text (title/cat/desc/
   blurb/sub labels) lives under `ideas.<id>` in messages/{zh,en}.json. */
export const ideas: IdeaNode[] = [
  {
    id: "ai",
    tone: "var(--node-ai)",
    hex: "#b06bff",
    progress: 60,
    stars: "1.2k",
    updated: "2d",
    lang: "TypeScript",
    commits: 342,
    issues: 12,
    sub: [
      { key: "repoMemory", href: "#" },
      { key: "inlineReview", href: "#" },
      { key: "testGen", href: "#" },
    ],
  },
  {
    id: "flow",
    tone: "var(--node-flow)",
    hex: "#2bff88",
    progress: 75,
    stars: "860",
    updated: "5h",
    lang: "Rust",
    commits: 489,
    issues: 7,
    sub: [
      { key: "nodeCanvas", href: "#" },
      { key: "toolRouting", href: "#" },
      { key: "runReplay", href: "#" },
    ],
  },
  {
    id: "radar",
    tone: "var(--node-radar)",
    hex: "#2ee6f6",
    progress: 40,
    stars: "410",
    updated: "1d",
    lang: "Go",
    commits: 211,
    issues: 23,
    sub: [
      { key: "liveFeed", href: "#" },
      { key: "repoHealth", href: "#" },
      { key: "trends", href: "#" },
    ],
  },
  {
    id: "blog",
    tone: "var(--node-blog)",
    hex: "#ff2d9b",
    progress: 80,
    stars: "2.4k",
    updated: "8h",
    lang: "MDX",
    commits: 156,
    issues: 3,
    sub: [
      { key: "buildingInPublic", href: "#" },
      { key: "aiNotes", href: "#" },
      { key: "rssFeed", href: "#" },
    ],
  },
  {
    id: "os",
    tone: "var(--node-os)",
    hex: "#ffae3a",
    progress: 30,
    stars: "320",
    updated: "3d",
    lang: "Various",
    commits: 98,
    issues: 41,
    sub: [
      { key: "templates", href: "#" },
      { key: "bountyBoard", href: "#" },
      { key: "snippets", href: "#" },
    ],
  },
  {
    id: "git3d",
    tone: "var(--node-radar)",
    hex: "#2ee6f6",
    progress: 18,
    stars: "95",
    updated: "6d",
    lang: "WebGL",
    commits: 64,
    issues: 9,
    sub: [
      { key: "branchOrbits", href: "#" },
      { key: "commitStars", href: "#" },
      { key: "flyThrough", href: "#" },
    ],
  },
  {
    id: "prompt",
    tone: "var(--node-ai)",
    hex: "#b06bff",
    progress: 52,
    stars: "640",
    updated: "12h",
    lang: "Python",
    commits: 178,
    issues: 5,
    sub: [
      { key: "versioning", href: "#" },
      { key: "abTest", href: "#" },
      { key: "export", href: "#" },
    ],
  },
  {
    id: "time",
    tone: "var(--node-blog)",
    hex: "#ff2d9b",
    progress: 12,
    stars: "48",
    updated: "9d",
    lang: "TypeScript",
    commits: 41,
    issues: 14,
    sub: [
      { key: "snapshots", href: "#" },
      { key: "diffView", href: "#" },
      { key: "restore", href: "#" },
    ],
  },
  {
    id: "stack",
    tone: "var(--node-flow)",
    hex: "#2bff88",
    progress: 100,
    stars: "1.6k",
    updated: "1d",
    lang: "Shell",
    commits: 523,
    issues: 2,
    sub: [
      { key: "dotfiles", href: "#" },
      { key: "secrets", href: "#" },
      { key: "oneCommand", href: "#" },
    ],
  },
];
